configuration:                 # ???? ??
  message:
    internationalization:      # ??? ???
      enabled: true
      parameter-name: lang     # URL ???? ??(Locale)

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true