configuration:                 # 프로젝트 환경설정
  message:
    internationalization:      # 국제화 옵션
      enabled: true
      parameter-name: lang     # URL 파라미터 명(Locale)

spring:
  profiles:
    active: local
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
  devtools:
    livereload:
      enabled: true